// Code generated by mockery v2.15.0. DO NOT EDIT.

package validation

import mock "github.com/stretchr/testify/mock"

// MockRule is an autogenerated mock type for the Rule type
type MockRule struct {
	mock.Mock
}

// Run provides a mock function with given fields: password
func (_m *MockRule) Run(password Password) bool {
	ret := _m.Called(password)

	var r0 bool
	if rf, ok := ret.Get(0).(func(Password) bool); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewMockRule interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRule creates a new instance of MockRule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRule(t mockConstructorTestingTNewMockRule) *MockRule {
	mock := &MockRule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
